<?php
require __DIR__ . "./header.php";
require __DIR__ . "./footer.php";
?>

<div>
    <h1>Lorem ipsum dolor sit amet</h1>
    <br>
    <br>
    <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ab atque error laborum natus odio placeat provident quo soluta, voluptatibus? Atque consectetur dignissimos esse explicabo iste nemo, nobis tempora voluptates?</span><span>Accusamus at autem earum, ex iusto laborum natus officiis perferendis quam quas, quo suscipit temporibus vel. Ad consectetur doloremque doloribus, eaque impedit inventore libero nisi, possimus quo reprehenderit sequi veritatis!</span><span>Aliquid aut consequuntur corporis, cupiditate incidunt labore maxime odio perferendis sapiente voluptates. Adipisci aliquam beatae consectetur cum cumque delectus dolor eum ipsam minus nobis obcaecati odio placeat, praesentium rerum voluptate.</span><span>Accusantium ad alias amet, atque cupiditate, debitis dolor dolores doloribus ducimus eligendi enim excepturi expedita hic magni minima modi nesciunt numquam omnis rem repellat sequi sit soluta velit vero vitae!</span><span>Blanditiis consequuntur distinctio dolorum ea eligendi, est eveniet expedita inventore maxime necessitatibus nulla officiis omnis optio, quos, veritatis. Adipisci asperiores aspernatur dolor esse ipsa modi natus obcaecati perferendis saepe totam.</span><span>Cumque, eum fuga labore laudantium magnam nulla qui ratione sint voluptatum. At cum dolorem, magnam nobis odit placeat quam repudiandae soluta? Adipisci consequuntur cumque dolor exercitationem modi nesciunt nihil tempore.</span><span>Animi impedit molestiae officiis suscipit velit. Consequatur ex laborum magni pariatur. Beatae dolore doloremque libero minima modi mollitia necessitatibus nisi perspiciatis possimus, qui, quo ratione saepe sint tempora ullam voluptas?</span><span>Alias corporis id natus quasi quidem! Ad aliquam aspernatur culpa delectus doloremque et fuga iusto nemo numquam quibusdam quisquam repellat reprehenderit rerum, ullam unde. Alias eum fugit impedit odit placeat.</span><span>Commodi debitis et harum id illo itaque rerum. Assumenda debitis nisi quos, repellat totam velit veniam? Animi blanditiis, distinctio dolorum error esse ipsum itaque magnam nostrum omnis temporibus! Dolorem, laboriosam.</span><span>Alias incidunt natus vero voluptatibus voluptatum! Blanditiis commodi deleniti dignissimos facere, in, iste labore molestiae pariatur qui quo ratione sint voluptates. A amet consectetur, error expedita nobis non nostrum temporibus.</span></p>
</div>
